spring.datasource.url=jdbc:postgresql://postgres:5432/mediashelf
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

jwt.accessTokenSecret=${JWT_ACCESS_TOKEN_SECRET}
jwt.refreshTokenSecret=${JWT_REFRESH_TOKEN_SECRET}

aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.s3.region=${AWS_S3_REGION}
aws.s3.bucket=${AWS_S3_BUCKET}